version: '2.0'
services:
  dataqueue:
    build: ./dataqueue
    ports:
    - "5001:5000"
    volumes:
    - .:/src
  datamanager:
    build: ./datamanager
    ports:
    - "5000:5000"
    volumes:
    - .:/src